### ISSUE TITLE
Using Proxy with Flurl or HttpClient

### ISSUE THREAD

**Issue by ngoquoctoandev** [lenniebriscoe/interview#1]
First, forgive me for creating a new issue in the wrong place. But I can't find your contact information anywhere.
I'm a big fan of HttpClient, especially the Flurl wrapper. However, I have the following problem. I access an API resource, where they limit the number of requests per IP per day. I thought of a solution using 3rd party Proxy to access. Unfortunately, my knowledge is limited, and the documentation I find online is not very much about this, of course, HttpClient (or Flurl) is not designed to do this. I want every 5 or 10 requests to automatically change to a new proxy to avoid blocking access.
Thank you for your interest, we look forward to hearing from you.

**Comment by lenniebriscoe** [comment]
Question not related to the repo and therefore closed. Please see the answer to your Stackoverflow post for a response.

**Comment by ngoquoctoandev** [comment]
I've scoured SO but none of the answers solved the problem with Flurl. Can you help me please?
